# Generated by Django 4.2.20 on 2025-03-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel_gen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aistory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='概要'),
        ),
    ]
