# Generated by Django 4.2.20 on 2025-03-12 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel_gen', '0002_aistory_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aistory',
            name='description',
        ),
    ]
