# Generated by Django 4.2.20 on 2025-03-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel_gen', '0003_remove_aistory_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicsettingdata',
            name='atmosphere',
        ),
        migrations.RemoveField(
            model_name='basicsettingdata',
            name='emotional_expressions',
        ),
        migrations.RemoveField(
            model_name='basicsettingdata',
            name='formatted_content',
        ),
        migrations.RemoveField(
            model_name='basicsettingdata',
            name='love_expressions',
        ),
        migrations.RemoveField(
            model_name='basicsettingdata',
            name='mental_elements',
        ),
        migrations.RemoveField(
            model_name='basicsettingdata',
            name='past_mysteries',
        ),
        migrations.RemoveField(
            model_name='basicsettingdata',
            name='plot_pattern',
        ),
        migrations.RemoveField(
            model_name='basicsettingdata',
            name='raw_content',
        ),
        migrations.RemoveField(
            model_name='basicsettingdata',
            name='sensual_expressions',
        ),
        migrations.RemoveField(
            model_name='basicsettingdata',
            name='social_elements',
        ),
        migrations.RemoveField(
            model_name='basicsettingdata',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='basicsettingdata',
            name='time_and_place',
        ),
        migrations.RemoveField(
            model_name='basicsettingdata',
            name='world_setting',
        ),
        migrations.AddField(
            model_name='basicsettingdata',
            name='basic_setting_data',
            field=models.TextField(blank=True, verbose_name='基本設定データ'),
        ),
    ]
