# Generated by Django 4.2.20 on 2025-03-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel_gen', '0004_remove_basicsettingdata_atmosphere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicsettingdata',
            name='emotional_data',
            field=models.JSONField(blank=True, null=True, verbose_name='情緒的要素データ'),
        ),
        migrations.AddField(
            model_name='basicsettingdata',
            name='integrated_data',
            field=models.JSONField(blank=True, null=True, verbose_name='統合データ'),
        ),
        migrations.AddField(
            model_name='basicsettingdata',
            name='mystery_data',
            field=models.JSONField(blank=True, null=True, verbose_name='謎データ'),
        ),
        migrations.AddField(
            model_name='basicsettingdata',
            name='plot_data',
            field=models.JSONField(blank=True, null=True, verbose_name='プロットデータ'),
        ),
        migrations.AddField(
            model_name='basicsettingdata',
            name='style_data',
            field=models.JSONField(blank=True, null=True, verbose_name='文体データ'),
        ),
        migrations.AddField(
            model_name='basicsettingdata',
            name='theme_data',
            field=models.JSONField(blank=True, null=True, verbose_name='テーマデータ'),
        ),
        migrations.AddField(
            model_name='basicsettingdata',
            name='time_place_data',
            field=models.JSONField(blank=True, null=True, verbose_name='時代と場所データ'),
        ),
        migrations.AddField(
            model_name='basicsettingdata',
            name='world_setting_data',
            field=models.JSONField(blank=True, null=True, verbose_name='世界観データ'),
        ),
    ]
