# Generated by Django 4.2.20 on 2025-03-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel_gen', '0005_basicsettingdata_emotional_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aistory',
            name='catchphrase',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='キャッチコピー'),
        ),
        migrations.AddField(
            model_name='aistory',
            name='summary',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='あらすじ'),
        ),
    ]
