name: Dify API Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DIFY_API_KEY_BASIC_SETTING_DATA: ${{ secrets.DIFY_API_KEY_BASIC_SETTING_DATA }}
      DIFY_API_KEY_BASIC_SETTING: ${{ secrets.DIFY_API_KEY_BASIC_SETTING }}
      DIFY_API_KEY_CHARACTER_DETAIL: ${{ secrets.DIFY_API_KEY_CHARACTER_DETAIL }}
      DIFY_API_KEY_PLOT_DETAIL: ${{ secrets.DIFY_API_KEY_PLOT_DETAIL }}
      DIFY_API_KEY_EPISODE_DETAIL: ${{ secrets.DIFY_API_KEY_EPISODE_DETAIL }}
      DIFY_API_KEY_EPISODE_CONTENT: ${{ secrets.DIFY_API_KEY_EPISODE_CONTENT }}
      DIFY_API_KEY_TITLE: ${{ secrets.DIFY_API_KEY_TITLE }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pytest-mock requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run unit tests with pytest
      run: |
        pytest TEST/DifyAPI/ -v

    - name: Generate test coverage report
      run: |
        pytest TEST/DifyAPI/ --cov=backend.novel_gen.dify_api --cov-report=xml

    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
